# AI Control System - Main Docker Compose
# This file provides a convenient way to run the development environment
# For production, use: docker-compose -f docker/docker-compose.prod.yml up

version: '3.8'

# Include the development configuration
# Usage: docker-compose up -d
# This will use the development configuration by default

services:
  # This file serves as a convenience wrapper
  # The actual services are defined in docker/docker-compose.dev.yml
  _placeholder:
    image: alpine:latest
    command: ["echo", "Please use: make dev or docker-compose -f docker/docker-compose.dev.yml up"]