"""Add dashboard models

Revision ID: 215dd563e3d2
Revises: a30e75af9e64
Create Date: 2025-08-20 17:38:59.040654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '215dd563e3d2'
down_revision: Union[str, None] = 'a30e75af9e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('widget_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('preview_image', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_widget_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_templates'))
    )
    op.create_index(op.f('ix_widget_templates_name'), 'widget_templates', ['name'], unique=False)
    op.create_table('dashboard_data_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('connection_string', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('datacode_script', sa.Text(), nullable=True),
    sa.Column('script_parameters', sa.JSON(), nullable=True),
    sa.Column('cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('cache_ttl', sa.Integer(), nullable=False),
    sa.Column('last_cache_update', sa.DateTime(), nullable=True),
    sa.Column('cached_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_data_sources_dashboard_id_dashboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_data_sources'))
    )
    op.create_table('dashboard_shares',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=False),
    sa.Column('shared_by', sa.BigInteger(), nullable=False),
    sa.Column('shared_with', sa.BigInteger(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_shares_dashboard_id_dashboards')),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], name=op.f('fk_dashboard_shares_shared_by_users')),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], name=op.f('fk_dashboard_shares_shared_with_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_shares'))
    )
    op.create_table('dashboard_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.Column('widgets_config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_dashboard_versions_created_by_users')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_versions_dashboard_id_dashboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_versions'))
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=False),
    sa.Column('widget_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('data_source_id', sa.BigInteger(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('last_refresh', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_widgets_dashboard_id_dashboards')),
    sa.ForeignKeyConstraint(['data_source_id'], ['dashboard_data_sources.id'], name=op.f('fk_dashboard_widgets_data_source_id_dashboard_data_sources')),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], name=op.f('fk_dashboard_widgets_widget_id_widgets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_widgets'))
    )
    # Сначала удаляем внешние ключи
    op.drop_constraint(op.f('fk_widgets_widget_type_id_widget_types'), 'widgets', type_='foreignkey')
    op.drop_constraint(op.f('fk_widgets_dashboard_id_dashboards'), 'widgets', type_='foreignkey')
    
    # Теперь удаляем таблицы
    op.drop_table('dashboard_datas')
    op.drop_table('widget_types')
    op.drop_table('data_sources')
    op.add_column('dashboards', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('dashboards', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('dashboards', sa.Column('layout_config', sa.JSON(), nullable=True))
    op.add_column('dashboards', sa.Column('theme', sa.String(length=50), nullable=False))
    op.add_column('dashboards', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('dashboards', sa.Column('is_template', sa.Boolean(), nullable=False))
    op.add_column('dashboards', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('dashboards', sa.Column('organization_id', sa.BigInteger(), nullable=True))
    op.add_column('dashboards', sa.Column('department_id', sa.BigInteger(), nullable=True))
    op.add_column('dashboards', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('dashboards', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=False)
    op.drop_constraint(op.f('fk_dashboards_owner_id_users'), 'dashboards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dashboards_department_id_departments'), 'dashboards', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('fk_dashboards_organization_id_organizations'), 'dashboards', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('fk_dashboards_user_id_users'), 'dashboards', 'users', ['user_id'], ['id'])
    op.drop_column('dashboards', 'owner_id')
    op.drop_column('dashboards', 'title')
    op.add_column('widgets', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('widgets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('widgets', sa.Column('widget_type', sa.String(length=100), nullable=False))
    op.add_column('widgets', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('widgets', sa.Column('icon', sa.String(length=255), nullable=True))
    op.add_column('widgets', sa.Column('default_config', sa.JSON(), nullable=True))
    op.add_column('widgets', sa.Column('schema', sa.JSON(), nullable=True))
    op.add_column('widgets', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('widgets', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('widgets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('widgets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_widgets_name'), 'widgets', ['name'], unique=False)
    op.drop_column('widgets', 'dashboard_id')
    op.drop_column('widgets', 'data')
    op.drop_column('widgets', 'widget_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('widget_type_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('widgets', sa.Column('data', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('widgets', sa.Column('dashboard_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_widgets_widget_type_id_widget_types'), 'widgets', 'widget_types', ['widget_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_widgets_dashboard_id_dashboards'), 'widgets', 'dashboards', ['dashboard_id'], ['id'])
    op.drop_index(op.f('ix_widgets_name'), table_name='widgets')
    op.drop_column('widgets', 'updated_at')
    op.drop_column('widgets', 'created_at')
    op.drop_column('widgets', 'is_system')
    op.drop_column('widgets', 'is_active')
    op.drop_column('widgets', 'schema')
    op.drop_column('widgets', 'default_config')
    op.drop_column('widgets', 'icon')
    op.drop_column('widgets', 'category')
    op.drop_column('widgets', 'widget_type')
    op.drop_column('widgets', 'description')
    op.drop_column('widgets', 'name')
    op.add_column('dashboards', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('dashboards', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_dashboards_user_id_users'), 'dashboards', type_='foreignkey')
    op.drop_constraint(op.f('fk_dashboards_organization_id_organizations'), 'dashboards', type_='foreignkey')
    op.drop_constraint(op.f('fk_dashboards_department_id_departments'), 'dashboards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dashboards_owner_id_users'), 'dashboards', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_column('dashboards', 'updated_at')
    op.drop_column('dashboards', 'created_at')
    op.drop_column('dashboards', 'department_id')
    op.drop_column('dashboards', 'organization_id')
    op.drop_column('dashboards', 'user_id')
    op.drop_column('dashboards', 'is_template')
    op.drop_column('dashboards', 'is_public')
    op.drop_column('dashboards', 'theme')
    op.drop_column('dashboards', 'layout_config')
    op.drop_column('dashboards', 'description')
    op.drop_column('dashboards', 'name')
    op.create_table('data_sources',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('connection_string', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_table('widget_types',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_types')),
    sa.UniqueConstraint('name', name=op.f('uq_widget_types_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dashboard_datas',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_datas_dashboard_id_dashboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_datas'))
    )
    op.drop_table('dashboard_widgets')
    op.drop_table('dashboard_versions')
    op.drop_table('dashboard_shares')
    op.drop_table('dashboard_data_sources')
    op.drop_index(op.f('ix_widget_templates_name'), table_name='widget_templates')
    op.drop_table('widget_templates')
    # ### end Alembic commands ###
