"""Add KPI models

Revision ID: beed956b677a
Revises: 215dd563e3d2
Create Date: 2025-08-20 19:21:14.687105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beed956b677a'
down_revision: Union[str, None] = '215dd563e3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('kpi_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_kpi_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_templates'))
    )
    op.create_index(op.f('ix_kpi_templates_name'), 'kpi_templates', ['name'], unique=False)
    op.create_table('kpis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('data_source', sa.JSON(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('previous_period_days', sa.Integer(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('kpi_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_calculation', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_kpis_created_by_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_kpis_department_id_departments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_kpis_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpis'))
    )
    op.create_index(op.f('ix_kpis_name'), 'kpis', ['name'], unique=False)
    op.create_table('kpi_calculations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('calculation_id', sa.String(length=255), nullable=False),
    sa.Column('kpi_id', sa.BigInteger(), nullable=True),
    sa.Column('calculated_by', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculation_metadata', sa.JSON(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], name=op.f('fk_kpi_calculations_calculated_by_users')),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], name=op.f('fk_kpi_calculations_kpi_id_kpis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_calculations'))
    )
    op.create_index(op.f('ix_kpi_calculations_calculation_id'), 'kpi_calculations', ['calculation_id'], unique=True)
    op.create_table('kpi_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('kpi_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_kpi_schedules_created_by_users')),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], name=op.f('fk_kpi_schedules_kpi_id_kpis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_schedules'))
    )
    op.create_table('kpi_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('kpi_id', sa.BigInteger(), nullable=True),
    sa.Column('calculation_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['kpi_calculations.id'], name=op.f('fk_kpi_notifications_calculation_id_kpi_calculations')),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], name=op.f('fk_kpi_notifications_kpi_id_kpis')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kpi_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_notifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_notifications')
    op.drop_table('kpi_schedules')
    op.drop_index(op.f('ix_kpi_calculations_calculation_id'), table_name='kpi_calculations')
    op.drop_table('kpi_calculations')
    op.drop_index(op.f('ix_kpis_name'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_kpi_templates_name'), table_name='kpi_templates')
    op.drop_table('kpi_templates')
    # ### end Alembic commands ###
