"""empty message

Revision ID: e6813794edab
Revises: 596d2a8fbb37
Create Date: 2025-07-07 14:33:19.441630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6813794edab'
down_revision: Union[str, None] = '596d2a8fbb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq_users_login'), 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_login'), 'users', type_='unique')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
