// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  BlockComment = 2,
  Script = 3,
  Statement = 4,
  Expr = 6,
  Identifier = 7,
  Number = 8,
  String = 9
